queue_rules:
  - name: default
    merge_method: squash 
    queue_conditions:
      - check-success=build
      - check-success=it-test

pull_request_rules:
  - name: Make sure PR are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge queue).
    conditions: []
    actions:
      update:
  - name: Automatically merge backports to releases on succesful build
    conditions:
      - base~=^(release-)
      - head~=^mergify\/bp\/
      - "author=mergify[bot]"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge on CI success and review
    conditions:
      - base=master
      - "label=ready to merge"
      - "approved-reviews-by=@oss-approvers"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge release branch changes on CI success and release manager review
    conditions:
      - base~=^release-
      - "label=ready to merge"
      - "approved-reviews-by=@release-managers"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge PRs from maintainers on CI success and review
    conditions:
      - base=master
      - "label=ready to merge"
      - "author=@oss-approvers"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge autobump PRs on CI success
    conditions:
      - base~=^(master|release-)
      - "label~=autobump-*"
      - "author:spinnakerbot"
    actions:
      queue:
        name: default
      label:
        add: ["auto merged"]
  - name: Request reviews for autobump PRs on CI failure
    conditions:
      - base~=^(master|release-)
      - "label~=autobump-*"
      - base=master
    actions:
      request_reviews:
        teams: ["oss-approvers"]
