#!/bin/bash

#
# Copyright 2020 Armory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ROOT_DIR="$(
  cd "$(dirname "$0")" >/dev/null 2>&1 || exit 1
  pwd -P
)"

function log_invocation() {
  echo "$@" >> "$ROOT_DIR/../../../../build/test-results/kubectl_invocations"
}

function parse_args() {
  cmd=""
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      --kubeconfig=*) account_folder=$(echo "$1" | sed "s|--kubeconfig=$ROOT_DIR/||" | sed "s|/kubeconfig||") ;;
      -o) output_format="$2"; shift ;;
      *) cmd+=$1_ ;;
    esac
    shift
  done
  cmd=${cmd%?} # Delete last character, which would be an extra underscore (_)
}

log_invocation $@
parse_args $@
file=${account_folder}/$cmd.$output_format
[[ ! -f "$ROOT_DIR/$file" ]] && echo "File $ROOT_DIR/$file doesn't exist, it needs to be mocked" && exit 1
cat "$ROOT_DIR/$file"
