#CircleCI config schema is versioned. 
version: 2.1

# orbs are config packages to include.
orbs:
  gradle: circleci/gradle@1.0.11
  slack: circleci/slack@3.3.0

workflows:
  build_and_test:
    jobs:
      - build

jobs:
  build:
    machine: true
    parallelism: 12
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Open permissions on cache dir
          command: sudo chmod -R a+rwx /root
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys: 
            - gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - gradle-
      - run:
          name: Install
          command: |
            GRADLE="./gradlew -PenablePublishing=true --no-daemon --max-workers=12"
            export GRADLE_OPTS="-Xmx16g -Xms16g"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Assemble Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              $GRADLE assemble
            else
              echo -e 'WARN: Only building on CircleCI'
              $GRADLE assemble
            fi


      - run:
          name: Build
          command: |
            GRADLE="./gradlew -PenablePublishing=true --no-daemon --max-workers=12"
            #export GRADLE_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
            export GRADLE_OPTS="-Xmx16g -Xms16g"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Build Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              $GRADLE build javadoc
            else
              echo -e 'WARN: Only building on CircleCI'
              $GRADLE build
            fi
      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}
      #- slack/notify


