#!/bin/bash
#
# Daemon Name: clouddriver
#
# chkconfig: 345 91 9
# description: # description here

# Source function library.
. /etc/init.d/functions

daemon=clouddriver
# ** edit the line below - this is the command to start your service **
prog="/opt/clouddriver/bin/clouddriver"
lockfile=/var/lock/subsys/$daemon
PID_FILE="/var/run/${daemon}.pid"


start() {
    #Make some checks for requirements before continuing

    # Start our daemon daemon
    echo -n $"Starting $daemon ($prog): "
    MODE=production nohup $prog < /dev/null > /var/log/spinnaker/${daemon}/${daemon}.log 2>&1 &
    echo $! > "$PID_FILE"
    RETVAL=$?
    echo

    #If all is well touch the lock file
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Shutting down $daemon: "
    killproc -p $PID_FILE
    RETVAL=$?
    echo

    #If all is well remove the pidfile and the lockfile
    [ $RETVAL -eq 0 ] && rm -f $PID_FILE && rm -f $lockfile
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p $PID_FILE $daemon
        ;;
  restart)
        stop
        start
        ;;
   *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
