apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 'index.docker.io/library/nginx:1.14.0'
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp/mounted
              name: mounted
      volumes:
        - name: mounted
