spring:
  application:
    name: clouddriver

services:
  fiat:
    enabled: false
    baseUrl: http://localhost:7003
  front50:
    enabled: true
    baseUrl: http://localhost:8080

redis:
  enabled: false
