name: Kubernetes Integration Tests

on: workflow_call

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  it-test-kubernetes:
    strategy:
      matrix:
        kubernetes-image:
          - "kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Java 8 for cross-compilation support. Setting it up before
      # Java 11 means it comes later in $PATH (because of how setup-java works)
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache on push
        if: github.event_name == 'push'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.sha }}
          # Restore build outputs from the previous commit (if successful), if current commit hasn't run successfully yet
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Cache on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Kubernetes Provider Integration Tests
        run: ./gradlew --build-cache :clouddriver-kubernetes:integrationTest -Pkubernetes-image=${{ matrix.kubernetes-image }}
