name: Kubernetes Integration Tests

on: workflow_call

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  it-test-kubernetes:
    strategy:
      matrix:
        kubernetes-image:
          - "kindest/node:v1.28.0@sha256:9f3ff58f19dcf1a0611d11e8ac989fdb30a28f40f236f59f0bea31fb956ccf5c"
          - "kindest/node:v1.27.3@sha256:9dd3392d79af1b084671b05bcf65b21de476256ad1dcc853d9f3b10b4ac52dde"
          - "kindest/node:v1.26.6@sha256:5e5d789e90c1512c8c480844e0985bc3b4da4ba66179cc5b540fe5b785ca97b5"
          - "kindest/node:v1.25.11@sha256:ca7371d5d1f680778e40e9bcbbea06c3c61ac6f0e1a29cba5c58ff2dae1ba7f5"
          - "kindest/node:v1.24.15@sha256:24473777a1eef985dc405c23ab9f4daddb1352ca23db60b75de9e7c408096491"
          - "kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac"
          - "kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047"
          - "kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6"
          - "kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9"
          - "kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Java 8 for cross-compilation support. Setting it up before
      # Java 11 means it comes later in $PATH (because of how setup-java works)
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Cache on push
        if: github.event_name == 'push'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.sha }}
          # Restore build outputs from the previous commit (if successful), if current commit hasn't run successfully yet
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Cache on pull_request
        if: github.event_name == 'pull_request'
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-cd-it-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-cd-it-${{ github.event.before }}
      - name: Kubernetes Provider Integration Tests
        run: |
          version=$(echo '${{ matrix.kubernetes-image }}' | grep -o 'v[0-9]*\.[0-9]*')
          ./gradlew --build-cache :clouddriver-kubernetes:integrationTest -Pkubernetes-image=${{ matrix.kubernetes-image }} -Pkubernetes-version=${version}
